### ISSUE TITLE
Better distinction between closed and open discussions

### ISSUE THREAD

**Issue by naps62** [subvisual/council#123]
Since we now have more open discussions than what fits on my laptop's screen, I found another problem

I can't see the "Closed discussions" title, so I have to scroll. But that makes it harder to distinguish where the open discussions show up, and makes the scrollbar unnecessarily large, when I probably only want to see the open ones

My suggestion: Only load open discussions by default, and have a button or some other page where we could see closed ones. This would also make the whole thing faster, since we would only be loading open discussions
@johnny1337 what do you think?

**Comment by joaojusto** [comment]
This is already discussed, the closed discussion should have opacity. On top of that what you are suggesting might as well make sense

**Comment by naps62** [comment]
I know they should have opacity. That still wouldn't solve the problem I had here
