### ISSUE TITLE
Wrong spacing on 'Open Discussions' and 'Closed Discussions' labels

### ISSUE THREAD

**Issue by joaojusto** [subvisual/council#133]
Same issue as #130. 
They should have the same spacing to bottom as they have from top.

![screen shot 2015-02-26 at 16 43 50](https://cloud.githubusercontent.com/assets/4236592/6396501/bc872e04-bdd6-11e4-8600-9b9b596ea622.png)

**Comment by bsonntag** [comment]
@joaojusto I believe this is already fixed.

![screenshot from 2015-06-30 14 44 44](https://cloud.githubusercontent.com/assets/6205451/8432263/ef5f847c-1f36-11e5-82a7-51bdf15af744.png)
